dist: trusty
language: node_js
node_js:
  - "8.12.0"
install: 
  - npm install
script: 
  - ./node_modules/.bin/eslint .
#  - ./node_modules/.bin/_mocha
#  - npm install -g istanbul
#  - istanbul check-coverage --statements 100 --branches 80 --functions 100 --lines 100