dist: trusty
language: node_js
node_js:
  - "8.12.0"
env:
  - TEST_MNEMONIC="kiwi just service vital feature rural vibrant copy pledge useless fee forum"
install: 
  - npm install
  - npm install -g ganache-cli
script: 
  - ./node_modules/.bin/eslint .
  - ganache-cli -p 7545 -m "kiwi just service vital feature rural vibrant copy pledge useless fee forum" > ~/ganache.log &
  - sleep 10
  - cat ~/ganache.log
  - ./node_modules/.bin/_mocha
#  - npm install -g istanbul
#  - istanbul check-coverage --statements 100 --branches 80 --functions 100 --lines 100